### ISSUE TITLE
Not available on rubygems

### ISSUE THREAD

**Issue by kevinprince** [planio-gmbh/rackstash#2]
Just tried to install from rubygems and the gem is not listed there

**Comment by meineerde** [comment]
I just pushed the current version of Rackstash as version v0.1.0 to rubygems.org at https://rubygems.org/gems/rackstash/versions/0.1.0.

Sorry for the overly long reaction time. I always wanted to actually fix this project / gem to be more up-to-date, to not be tied to Rails and ActiveSupport, to actually work with pure Rack applications, and to support more diverse logging setups.

I started working on this as a full rewrite / rearchitecture of Rackstash in https://github.com/meineerde/rackstash which will eventually be released as Rackstash v0.2.0. The v0.1.x codebase will probably not be significantly updated after that since all new development will happen in https://github.com/meineerde/rackstash.
